knife4j:
  enable: true
  production: true

# 默认缓存
cacheName: redis

# spring配置
spring:
  application:
    name: fileListen
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  data:
    redis:
      timeout: 30000
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 10
          max-wait: 5000
          time-between-eviction-runs: 600000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      p6spy: true
      strict: false
      hikari:
        # 最大连接池数量
        maxPoolSize: 20
        # 最小空闲线程数量
        minIdle: 10
        # 配置获取连接等待超时的时间
        connectionTimeout: 30000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 600000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 1800000
        # 连接测试query（配置检测连接是否有效）
        connectionTestQuery: SELECT 1
        # 多久检查一次连接的活性
        keepaliveTime: 30000

# mybatis配置
mybatis-plus:
  mapper-locations: classpath*:/com/cjree/**/*.xml
  configuration:
    database-id: mysql
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    cache-enabled: false
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: available
      logic-delete-value: "'NO'"
      logic-not-delete-value: "'YES'"

# mongo打印sql级别
logging:
  level:
    org.springframework.data.mongodb.core: INFO

